
frameworkVersion: '2'

service: ServerlessSampleLambdaProject

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage}
  lambdaHashingVersion: 20201221
  region: ap-northeast-1
  logRetentionInDays: 1
  environment:
    STAGE: ${opt:stage}

plugins:
  - serverless-plugin-conditional-functions

custom:
  hello_enabled:
    stg: false
    dev: true
  params: ${file(./serverless-${opt:stage}.yml)}

functions:
  hello:
    enabled: '"${self:provider.stage}" == "dev"'
    handler: handler.hello
    events:
      - cloudwatchLog:
          logGroup: /aws/serverless_sample_${opt:stage}
          filter: 'DEBUG'
