
service: ServerlessSampleLambdaProject
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: ap-northeast-1
  

functions:
  hello:
    handler: handler.hello
